---
AWSTemplateFormatVersion: 2010-09-09
Description: "RDE API Table Stack"
Parameters:
  TableName:
    Type: String
    Default: ""
  MappingTableName:
    Type: String
    Default: ""
  DataTableRCU:
    Type: Number
    Default: 5
  DataTableWCU:
    Type: Number
    Default: 5
  MappingTableRCU:
    Type: Number
    Default: 5
  MappingTableWCU:
    Type: Number
    Default: 5
Conditions:
  HasTableName: !Not [ !Equals ["", !Ref TableName] ]
  HasMappingTableName: !Not [ !Equals ["", !Ref MappingTableName] ]

Resources:
  Table:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !If [HasTableName, !Ref TableName, !Ref "AWS::NoValue"]
      AttributeDefinitions:
      - AttributeName: "person_id"
        AttributeType: "S"
      - AttributeName: "sort_key"
        AttributeType: "S"
      KeySchema:
      - AttributeName: "person_id"
        KeyType: "HASH"
      - AttributeName: "sort_key"
        KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: !Ref DataTableRCU
        WriteCapacityUnits: !Ref DataTableWCU
    
  MappingTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !If [HasMappingTableName, !Ref MappingTableName, !Ref "AWS::NoValue"]
      BillingMode : "PAY_PER_REQUEST"
      AttributeDefinitions:
      - AttributeName: "sso_id"
        AttributeType: "S"
      KeySchema:
      - AttributeName: "sso_id"
        KeyType: "HASH"
      #ProvisionedThroughput:
      #  ReadCapacityUnits: !Ref MappingTableRCU
      #  WriteCapacityUnits: !Ref MappingTableWCU
      

Outputs:
  TableName:
    Description: RDE DDB Table  
    Value: !Ref Table
  MappingTableName:
    Description: RDE DDB Table  
    Value: !Ref MappingTable
